language: node_js
dist: trusty

env:
  - TEST_COMMAND=coverage
  - TEST_COMMAND=e2e

addons:
  chrome: stable

branches:
  only:
    - master
    - trx-reporter
    - /^rc-.*$/
    - /^[0-9]+\.[0-9]+\.[0-9]+.*/

before_install:
 - sudo cp ./ssl/skyux-ca.crt /usr/local/share/ca-certificates/skyux-ca.crt
 - sudo update-ca-certificates

before_script:
  - "export CHROME_BIN=chromium-browser"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script: "npm run lint && npm run $TEST_COMMAND"

after_success:
  - bash <(curl -s https://codecov.io/bash) -s coverage/builder -F builder
  - bash <(curl -s https://codecov.io/bash) -s coverage/runtime/ -F runtime
  - bash <(curl -s https://codecov.io/bash) -s coverage/src-app/ -F srcapp
